FROM node:18-alpine
WORKDIR /app
COPY package.json yarn.lock ./
# COPY package.json package-lock.json ./
RUN yarn install
# RUN npm install
COPY . .
EXPOSE 3000
CMD ["yarn", "start"]
# CMD ["npm", "start"]